#!/bin/bash
root -l 'plotROC_eta0to2.C(0,"jetNewID_AK4PFCHS.txt","jetOldID_AK4PFCHS.txt","AK4PFjetsCHS")'
root -l 'plotROC_eta2to3.C(0,"jetNewID_AK4PFCHS.txt","jetOldID_AK4PFCHS.txt","AK4PFjetsCHS")'
root -l 'plotROC_eta3to5.C(0,"jetNewID_AK4PFCHS.txt","jetOldID_AK4PFCHS.txt","AK4PFjetsCHS")'
root -l 'plotROC_eta0to2.C(0,"jetNewID_AK4PF.txt","jetOldID_AK4PF.txt","AK4PFjets")'
root -l 'plotROC_eta2to3.C(0,"jetNewID_AK4PF.txt","jetOldID_AK4PF.txt","AK4PFjets")'
root -l 'plotROC_eta3to5.C(0,"jetNewID_AK4PF.txt","jetOldID_AK4PF.txt","AK4PFjets")'
root -l 'plotROC_eta0to2.C(2,"jetNewID_AK4PFCHS_newBinning2.txt","jetNewID_AK4PFCHS_oldBinning2.txt","AK4PFjetsCHS_binning")'
root -l 'plotROC_eta2to3.C(2,"jetNewID_AK4PFCHS_newBinning2.txt","jetNewID_AK4PFCHS_oldBinning2.txt","AK4PFjetsCHS_binning")'
root -l 'plotROC_eta3to5.C(2,"jetNewID_AK4PFCHS_newBinning2.txt","jetNewID_AK4PFCHS_oldBinning2.txt","AK4PFjetsCHS_binning")'
root -l 'plotROC_eta0to2.C(3,"jetNewID_AK4PFCHS_newBinning2.txt","jetOldID_AK4PFCHS.txt","AK4PFjetsCHS_1610")'
root -l 'plotROC_eta2to3.C(3,"jetNewID_AK4PFCHS_newBinning2.txt","jetOldID_AK4PFCHS.txt","AK4PFjetsCHS_1610")'
root -l 'plotROC_eta3to5.C(3,"jetNewID_AK4PFCHS_newBinning2.txt","jetOldID_AK4PFCHS.txt","AK4PFjetsCHS_1610")'
root -l 'plotROC_eta0to2.C(4,"jetNewID_AK4PFCHS_newBinning2.txt","jetNewID_AK4PFCHS.txt","AK4PFjetsCHS_1610_new")'
root -l 'plotROC_eta2to3.C(4,"jetNewID_AK4PFCHS_newBinning2.txt","jetNewID_AK4PFCHS.txt","AK4PFjetsCHS_1610_new")'
root -l 'plotROC_eta3to5.C(4,"jetNewID_AK4PFCHS_newBinning2.txt","jetNewID_AK4PFCHS.txt","AK4PFjetsCHS_1610_new")'